# Generated by Django 5.2.7 on 2025-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='temporary_default_password', max_length=128, null=True),
        ),
    ]
